[package]
name = "rust-cookbook"
version = "0.1.0"
edition = "2021"
authors = ["Alex Black <wa7@sa34.cx>"]
license = "MIT"
keywords = ["digitalocean", "telegram", "devops"]
readme = "README.md"

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
ansi_term = "0.12"
crossbeam = "0.8"